### ISSUE TITLE
ipv6 address check not work well

### ISSUE THREAD

**Issue by xiaoxiangjian** [TrevonWilkins/IP-Address-Checker#1]
print(checkIPAddress(ip="1111::8888"))
》》》Invalid IP Address

**Comment by TrevonWilkins** [comment]
Thank you. Source has been updated to support shortened IPv6 notation.

print(checkipaddress(ip="1111::8888"))
》》》('Valid IPv6 Address', '1111:0000:0000:0000:0000:0000:0000:8888')

*The function case has changed as well to all lowercase.
